# Generated by Django 4.1 on 2022-08-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_myclubuser_venue_event_attendees_alter_event_venue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="descriptions", new_name="description",
        ),
    ]
