# Generated by Django 4.1 on 2022-08-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_descriptions_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="email_adress",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="contact Phone"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="web",
            field=models.URLField(blank=True, verbose_name="Website Address"),
        ),
    ]
